### ISSUE TITLE
When printing......

### ISSUE THREAD

**Issue by DevBefell** [mew/SimpleStats#2]
![image](https://user-images.githubusercontent.com/54691311/85802906-c451dd00-b6fa-11ea-971a-e41aeced72f6.png)
It is probably because when printing it gets the stats when it prints a line, thus causing delays and thus causing that to happen

**Comment by mew** [comment]
Yeah. This happens because the stats command is ran asynchronously and it just prints each line in chat as soon as the line is ready. It's definitely possible (especially before lines that require calculations like SkyWars Level or Hypixel Level) for chat messages to show up in between.

**Comment by DevBefell** [comment]
Is there a way you can fix that?
