### ISSUE TITLE
Crashing my game as soon as I join Hypixel 

### ISSUE THREAD

**Issue by yanlin41020** [mew/SimpleStats#6]
https://paste.ee/p/0E5fo

**Comment by mew** [comment]
I will release a patch ASAP. Thank you! :)

**Comment by yanlin41020** [comment]
No problem. Thanks for the mod! I've become so reliant on this mod

**Comment by mew** [comment]
[Released a patch](https://github.com/mew/SimpleStats/releases/tag/1.3.1).
