### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by Kittiens** [mew/SimpleStats#9]
In 1.2, the stats mod would work instantly, but now, feels a little slower than usual. Could be Hypixel servers making it harder to run it.

**Comment by SecretPanda420** [comment]
We are looking into it. I'll see what I can do.

**Comment by SecretPanda420** [comment]
@fallenpugs can you try this build and let me know if this is any faster? i made some minor performance enhancements, im personally seeing a ~2300ms improvement.
[build](https://cdn.discordapp.com/attachments/562662826301194241/738012521641803817/SimpleStats-1.3.1.jar)

**Comment by Kittiens** [comment]
> @fallenpugs can you try this build and let me know if this is any faster? i made some minor performance enhancements, im personally seeing a ~2300ms improvement.
> [build](https://cdn.discordapp.com/attachments/562662826301194241/738012521641803817/SimpleStats-1.3.1.jar)

Yeah, it feels faster now. Thank you Collaborator @SecretPanda420
